// restaurants.ts
export interface Restaurant {
  id: string;
  name: string;
  address: string;
  neighborhood: string;
  logoImg: string;
  thumbnail: string;
  discount?: string;
  badge?: {
    text: string;
    subtext?: string;
    bgColor: string;
    textColor: string;
  };
  categories: string[];
  priceRange: 1 | 2 | 3 | 4; // $ to $$$$
  rating: number; // 1-5
  featured: boolean;
  popular: boolean;
  new: boolean;
  totalUsers?: number;
}

export const vancouverRestaurants: Restaurant[] = [
  {
    id: "cafe-il-nido",
    name: "CAFE IL NIDO",
    address: "780 Thurlow Street (Robson & Alberni St)",
    neighborhood: "Downtown",
    logoImg: "/images/logos/il-nido-logo.png",
    thumbnail: "/images/restaurants/il-nido.png",
    discount: "3X Points • $8 off $100 • $4 off $50",
    badge: {
      text: "Diners' Choice 2024",
      subtext: "Traditional Italian Cuisine since 1988",
      bgColor: "bg-purple-700",
      textColor: "text-white",
    },
    categories: ["Italian", "Featured", "Popular"],
    priceRange: 3,
    rating: 4.5,
    featured: true,
    popular: true,
    new: false,
    totalUsers: 2854,
  },
  {
    id: "super-thai-diy-hot-pot",
    name: "Super Thai DIY Hot Pot",
    address: "Burnaby • 3327 Kingsway",
    neighborhood: "Burnaby",
    logoImg: "/images/logos/super-thai-logo.png",
    thumbnail: "/images/restaurants/super-thai.png",
    discount: "8X Points",
    badge: {
      text: "",
      subtext: "NEW TRENDING",
      bgColor: "bg-yellow-500",
      textColor: "text-yellow-900",
    },
    categories: ["Thai", "Hotpot", "New"],
    priceRange: 2,
    rating: 4.3,
    featured: false,
    popular: true,
    new: true,
    totalUsers: 1835,
  },
  {
    id: "miku-vancouver",
    name: "Miku Vancouver",
    address: "200 Granville Street, Suite 70",
    neighborhood: "Downtown",
    logoImg: "/images/logos/miku-logo.png",
    thumbnail: "/images/restaurants/miku.png",
    discount: "2X Points • $10 off $120",
    badge: {
      text: "Premium",
      subtext: "Aburi Sushi & Japanese Cuisine",
      bgColor: "bg-indigo-800",
      textColor: "text-white",
    },
    categories: ["Japanese", "Sushi", "Featured", "Popular"],
    priceRange: 4,
    rating: 4.8,
    featured: true,
    popular: true,
    new: false,
    totalUsers: 3578,
  },
  {
    id: "phnom-penh",
    name: "Phnom Penh",
    address: "244 E Georgia St",
    neighborhood: "Chinatown",
    logoImg: "/images/logos/phnom-penh-logo.png",
    thumbnail: "/images/restaurants/phnom-penh.png",
    discount: "5X Points",
    badge: {
      text: "Local Favorite",
      subtext: "Cambodian & Vietnamese Cuisine",
      bgColor: "bg-green-700",
      textColor: "text-white",
    },
    categories: ["Cambodian", "Vietnamese", "Popular", "Noodles"],
    priceRange: 2,
    rating: 4.7,
    featured: false,
    popular: true,
    new: false,
    totalUsers: 4250,
  },
  {
    id: "dinesty-dumpling-house",
    name: "Dinesty Dumpling House",
    address: "1719 Robson St",
    neighborhood: "West End",
    logoImg: "/images/logos/dinesty-logo.png",
    thumbnail: "/images/restaurants/dinesty.png",
    discount: "4X Points • $6 off $80",
    badge: {
      text: "Soup Dumplings",
      subtext: "Authentic Shanghainese Cuisine",
      bgColor: "bg-red-700",
      textColor: "text-white",
    },
    categories: ["Chinese", "Dumplings", "Popular"],
    priceRange: 2,
    rating: 4.4,
    featured: false,
    popular: true,
    new: false,
    totalUsers: 3120,
  },
  {
    id: "liuyishou-hotpot",
    name: "Liuyishou Hotpot",
    address: "1542 Robson St",
    neighborhood: "West End",
    logoImg: "/images/logos/liuyishou-logo.png",
    thumbnail: "/images/restaurants/liuyishou.png",
    discount: "6X Points • $12 off $150",
    badge: {
      text: "Authentic",
      subtext: "Chongqing Style Hotpot",
      bgColor: "bg-red-600",
      textColor: "text-white",
    },
    categories: ["Chinese", "Hotpot", "Szechuan", "Featured"],
    priceRange: 3,
    rating: 4.3,
    featured: true,
    popular: false,
    new: false,
    totalUsers: 2870,
  },
  {
    id: "purebread",
    name: "Purebread",
    address: "159 W Hastings St",
    neighborhood: "Gastown",
    logoImg: "/images/logos/purebread-logo.png",
    thumbnail: "/images/restaurants/purebread.png",
    discount: "2X Points",
    badge: {
      text: "Best Bakery",
      subtext: "Artisanal Baked Goods",
      bgColor: "bg-amber-600",
      textColor: "text-white",
    },
    categories: ["Bakery", "Coffee", "Featured"],
    priceRange: 2,
    rating: 4.6,
    featured: true,
    popular: false,
    new: false,
    totalUsers: 2340,
  },
  {
    id: "beta5-chocolates",
    name: "BETA5 Chocolates",
    address: "409 Industrial Ave",
    neighborhood: "Mount Pleasant",
    logoImg: "/images/logos/beta5-logo.png",
    thumbnail: "/images/restaurants/beta5.png",
    discount: "3X Points",
    badge: {
      text: "Award-Winning",
      subtext: "Artisanal Chocolates & Pastries",
      bgColor: "bg-amber-800",
      textColor: "text-white",
    },
    categories: ["Bakery", "Dessert", "Featured"],
    priceRange: 3,
    rating: 4.7,
    featured: true,
    popular: false,
    new: false,
    totalUsers: 1890,
  },
  {
    id: "marutama-ramen",
    name: "Marutama Ramen",
    address: "780 Bidwell St",
    neighborhood: "West End",
    logoImg: "/images/logos/marutama-logo.png",
    thumbnail: "/images/restaurants/marutama.png",
    discount: "4X Points",
    badge: {
      text: "Fan Favorite",
      subtext: "Authentic Chicken Broth Ramen",
      bgColor: "bg-yellow-600",
      textColor: "text-white",
    },
    categories: ["Japanese", "Ramen", "Noodles", "Popular"],
    priceRange: 2,
    rating: 4.5,
    featured: false,
    popular: true,
    new: false,
    totalUsers: 3450,
  },
  {
    id: "danbo-ramen",
    name: "Ramen Danbo",
    address: "1833 W 4th Ave",
    neighborhood: "Kitsilano",
    logoImg: "/images/logos/danbo-logo.png",
    thumbnail: "/images/restaurants/danbo.png",
    discount: "3X Points • $5 off $60",
    badge: {
      text: "Authentic",
      subtext: "Fukuoka-Style Tonkotsu Ramen",
      bgColor: "bg-orange-700",
      textColor: "text-white",
    },
    categories: ["Japanese", "Ramen", "Noodles"],
    priceRange: 2,
    rating: 4.6,
    featured: false,
    popular: true,
    new: false,
    totalUsers: 3270,
  },
  {
    id: "sun-sui-wah",
    name: "Sun Sui Wah Seafood Restaurant",
    address: "3888 Main St",
    neighborhood: "Main Street",
    logoImg: "/images/logos/sun-sui-wah-logo.png",
    thumbnail: "/images/restaurants/sun-sui-wah.png",
    discount: "5X Points • $15 off $180",
    badge: {
      text: "Legendary",
      subtext: "Famous for Roast Squab & Dim Sum",
      bgColor: "bg-red-800",
      textColor: "text-white",
    },
    categories: ["Chinese", "Dim Sum", "Seafood", "Featured"],
    priceRange: 3,
    rating: 4.4,
    featured: true,
    popular: true,
    new: false,
    totalUsers: 4120,
  },
  {
    id: "szechuan-chongqing",
    name: "Szechuan Chongqing Seafood",
    address: "1668 W Broadway",
    neighborhood: "Fairview",
    logoImg: "/images/logos/szechuan-chongqing-logo.png",
    thumbnail: "/images/restaurants/szechuan-chongqing.png",
    discount: "4X Points",
    badge: {
      text: "Authentic Spice",
      subtext: "Traditional Szechuan Cuisine",
      bgColor: "bg-red-600",
      textColor: "text-white",
    },
    categories: ["Chinese", "Szechuan", "Seafood"],
    priceRange: 2,
    rating: 4.2,
    featured: false,
    popular: false,
    new: false,
    totalUsers: 2650,
  },
  {
    id: "the-old-spaghetti-factory",
    name: "The Old Spaghetti Factory",
    address: "53 Water St",
    neighborhood: "Gastown",
    logoImg: "/images/logos/spaghetti-factory-logo.png",
    thumbnail: "/images/restaurants/spaghetti-factory.png",
    discount: "2X Points • $5 off $50",
    badge: {
      text: "Family Favorite",
      subtext: "Italian-American Comfort Food",
      bgColor: "bg-green-600",
      textColor: "text-white",
    },
    categories: ["Italian", "Family", "Popular"],
    priceRange: 2,
    rating: 4.0,
    featured: false,
    popular: true,
    new: false,
    totalUsers: 5230,
  },
  {
    id: "hot-pot-palace",
    name: "Hot Pot Palace",
    address: "5300 No. 3 Rd",
    neighborhood: "Richmond",
    logoImg: "/images/logos/hot-pot-palace-logo.png",
    thumbnail: "/images/restaurants/hot-pot-palace.png",
    discount: "7X Points • $10 off $120",
    badge: {
      text: "NEW",
      subtext: "All-You-Can-Eat Premium Hotpot",
      bgColor: "bg-blue-600",
      textColor: "text-white",
    },
    categories: ["Chinese", "Hotpot", "New"],
    priceRange: 3,
    rating: 4.5,
    featured: false,
    popular: false,
    new: true,
    totalUsers: 1250,
  },
  {
    id: "saku-broadway",
    name: "Saku",
    address: "1773 Robson St",
    neighborhood: "West End",
    logoImg: "/images/logos/saku-logo.png",
    thumbnail: "/images/restaurants/saku.png",
    discount: "3X Points",
    badge: {
      text: "Specialty",
      subtext: "Japanese Tonkatsu",
      bgColor: "bg-indigo-600",
      textColor: "text-white",
    },
    categories: ["Japanese", "Specialty", "Featured"],
    priceRange: 2,
    rating: 4.4,
    featured: true,
    popular: false,
    new: false,
    totalUsers: 2340,
  },
  {
    id: "new-town-bakery",
    name: "New Town Bakery & Restaurant",
    address: "148 E Pender St",
    neighborhood: "Chinatown",
    logoImg: "/images/logos/new-town-logo.png",
    thumbnail: "/images/restaurants/new-town.png",
    discount: "2X Points",
    badge: {
      text: "Local Classic",
      subtext: "Famous for Apple Buns & Chinese Bakery",
      bgColor: "bg-yellow-700",
      textColor: "text-white",
    },
    categories: ["Chinese", "Bakery", "Dim Sum"],
    priceRange: 1,
    rating: 4.3,
    featured: false,
    popular: true,
    new: false,
    totalUsers: 3870,
  },
];
